// <auto-generated />
namespace Bravo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_artist_from_album : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_artist_from_album));
        
        string IMigrationMetadata.Id
        {
            get { return "201601232004559_remove_artist_from_album"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
